### ISSUE TITLE
Provide the unicef logo in the necessary format

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#10]
- [ ] square version (500px x 500px) 
- [ ] the rectangular version of the logo with a transparent background

![unicef_logotype_cyan_cmyk_300ppi_eng-fr-sp](https://user-images.githubusercontent.com/3488986/51462058-c4fd7b80-1d70-11e9-8332-5ccc6c612976.JPG)

**Comment by rowo** [comment]
This might be replaced with https://github.com/OpenSRP/opensrp-client-eusm/issues/11

**Comment by cafootitt** [comment]
Confirmed that this is replaced with #11, closing.
