### ISSUE TITLE
Inability to Login When Device is Offline

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#100]
EUSM Mobile will be updated to address an issue where users are unable to login when automatically logged out when in offline mode. This fix may have been implemented on OpenSRP and may just require updating of the core-libraries for EUSM.

**Comment by hamza-vd** [comment]
The offline login is working fine. The following steps have tested this
1. Set user session expiry to 1 min
2. Login into the app
3. Wait until logged out. 
4.  Disable internet connectivity and try login again
5. I Was able to login successfully.

**Comment by Mstjamush** [comment]
Not in a position to replicate this
