### ISSUE TITLE
Addition and Editing of Tasks

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#101]
**Beneficiary consultation**
- [x] The client desires to add a new task named `Beneficiary consultation`. This will be enabled for locations that that have inventories and will form part of the last part of the `service point check` task. The questions to be asked are:
- [x] Did you consult beneficiaries during your visit? Yes/No.
- [x]  Where a `No` response is given, the form will provide the option to save the form and exit.
- [x] Where a `Yes` response is given, the form will provide an additional 3 questions
- - - Describe who you consulted with. A text field will be provided to type in the name of the person consulted.
- - - What issues were raised ? A text field will be provided to type in the issues that were raised.
- - - Should you raise a flag for the issues raised? This should have the option `Yes` or `No`
- [x] Where `No` is selected the form provides the option to save the form and close it.
- [x] Where `Yes` is selected, the form provided the option to save the form and close it. At the point of saving the form the `Yes` response should trigger generation of a problem flag for the service point.

**Warehouse Form**
- [x] The client desires to capture additional details for service points where type is warehouse. Where the service point is a warehouse, the user will be presented with the following questions.
- - - Are there any expired supplies? (YES/NO)
- - - Are there any supplies which will expire in the next 3 months? (YES/NO) (If YES, provide a text box to capture the supplies are due for expiry)
- - - Is the storage space secured and guarded? (YES/NO)
- - - Are the storage conditions satisfactory (free from rodents, dry, properly stacked)? (YES/NO)
- - - Is the storage space in good condition? (YES/NO)
- - - Speak with the warehouse manager – are there any issues which require action? (YES/NO) (If yes, open text for explanation)

**Comment by samkanga** [comment]
@dubdabasoduba following the discussions with Gareth, I would like to add the point of investigation below so we can determine the ease of implementation.
- [ ] Gareth asked if instead of requiring the user to answer the question `Is this service point a warehouse?` and then providing the warehouse related questions, we have the system determining when a service point is a warehouse and providing the questions without requiring the users intervention.

**Comment by hamza-vd** [comment]
@samkanga 
1. Can you please mark which fields are mandatory and which aren't in the above list?
2. if `Should you raise a flag for the issues raised?` is answered `yes`, then the user will be prompted with the **Flag Problem** form right after the service check is saved or it should launch as soon as user selects Yes to thee question?
3. In the last task list mentioned above
    - Will these questions be part of the service point check or should they be included as a separate form?
    - We will check if that service point is a warehouse programmatically to show/hide this questioarie?

**Comment by samkanga** [comment]
@hamza-vd see my responses below:
1. Let's mark all the new questions mandatory since we either expect a Yes or No answer or an explanation.
2. This is similar to the scenario where a user completes a flag problem task. The expectation is that if a user answers Yes, a similar task to what we get when the flag problem task is raised will show. Let me know if we need a call on this.
3. Yes, the questions will be part of the service point check questions. Yes, we will have a skip logic to check the type of service point from the backend and if its a warehouse to show the warehouse questions and if its not to not show the questions.

**Comment by samkanga** [comment]
@hamza-vd EUSM team has requested that we separate the tasks from the service point check. As such the tasks will be as follows:

1. Service Point Check - Remains with the initial questions
2. Beneficiary Consultation - New task generated only when a service point has inventories. This is similar to the service point check logic.
3. Warehouse Check - New task generated only when a service point has inventories. This is similar to the service point check logic.

Kindly facilitate the changes above.

**Comment by samkanga** [comment]
This has passed QA.
