### ISSUE TITLE
Add Action and Goal to trigger generation of a problem flag

### ISSUE THREAD

**Issue by hamza-vd** [opensrp/opensrp-client-eusm#107]
The following Action and Goal need to be added to the plan definition templates to trigger the generation of a problem for a service point check flag

### Action
`{
  "identifier": "cecb3c88-3dc4-4fdc-8d13-92d37de73ad5",
  "prefix": 9,
  "title": "Complete Service Point Check With Problem",
  "description": "Completes Service Point Check Task With Problem",
  "code": "complete_service_point_with_flag_problem",
  "timingPeriod": {
    "start": "2021-07-24",
    "end": "2021-07-31"
  },
  "reason": "Routine",
  "goalId": "complete_service_point_with_flag_problem",
  "subjectCodableConcept": {
    "text": "Task"
  },
  "trigger": [
    {
      "type": "named-event",
      "name": "event-submission",
      "expression": {
        "description": "Trigger when a Flag Problem event is submitted",
        "expression": "questionnaire = 'service_point_check'"
      }
    }
  ],
  "condition": [
    {
      "kind": "applicability",
      "expression": {
        "description": "Problem Flagged",
        "expression": "$this.is(FHIR.QuestionnaireResponse)"
      }
    },
    {
      "kind": "applicability",
      "expression": {
        "description": "check consult_beneficiaries_flag field",
        "expression": "$this.item.where(linkId='consult_beneficiaries_flag').answer.value ='yes'"
      }
    }
  ],
  "definitionUri": "service_point_check.json",
  "dynamicValue": [
    {
      "path": "businessStatus",
      "expression": {
        "expression": "'has_problem'"
      }
    },
    {
      "path": "status",
      "expression": {
        "expression": "'Completed'"
      }
    }
  ],
  "type": "update"
}`

### Goal
`{
                "id": "complete_service_point_with_flag_problem",
                "description": "Complete check for a particular service point (100%) with flag problem within the Jurisdiction",
                "priority": "medium-priority",
                "target": [
                    {
                        "measure": "Percent of service points checked with flag problem",
                        "detail": {
                            "detailQuantity": {
                                "value": 100.0,
                                "comparator": "&amp;amp;amp;amp;amp;gt;",
                                "unit": "Percent"
                            }
                        },
                        "due": "2022-12-12"
                    }
                ]
            }`

**Comment by p-netm** [comment]
> "comparator": "&amp;amp;amp;amp;amp;gt;"

What is the unescaped value of this, or is this the way this should show up in the plan's payload?

@hamza-vd @samkanga

**Comment by hamza-vd** [comment]
It seems like a [Quantity.comparator](http://fhir-ru.github.io/datatypes-definitions.html#Quantity.comparator), but it is being used in the same way for other goals as well. cc: @bennsimon

**Comment by p-netm** [comment]
@hamza-vd  so should it be a `>` or  "&amp;amp;amp;amp;gt;"?

**Comment by p-netm** [comment]
Going to use `>` since its what is hardcoded for other goal comparators on web. I think it might be getting html-escaped in the backend.
