### ISSUE TITLE
Create logo for UNICEF EUSM

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#11]
Client wants to use the 177 icon for "Monitoring" in the logo. So this makes the app name a logo instead of text.

Can we work with this?

![image](https://user-images.githubusercontent.com/3488986/96034974-3db43d80-0e5a-11eb-9b62-81257ce5c650.png)

**Comment by cafootitt** [comment]
No longer blocked, client confirmed he wants to go with this approach.

**Comment by rowo** [comment]
@cafootitt Here's the handoff: https://marvelapp.com/prototype/1296hh24/screen/71758169/handoff

**Comment by cafootitt** [comment]
Thanks Roger
