### ISSUE TITLE
Enabling the Fix Problem Task

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#113]
We had disabled the `Fix Problem` task a while back when the client complained that it was cumbersome to close the ticket from the android client. The client has since advanced a request to have the same task closed from the Akuko dashboard. To facilitate this process, we need to enable the fix problem to facilitate the needed tests on Akuko. The `Fix Problem` task is generated whenever a problem is flagged on an inventory item.

**Comment by hamza-vd** [comment]
@samkanga 

We need to revert the changes made in the following comment to enable `fix_problem`  task again

- [ ] [Remove fix_problem action](https://github.com/opensrp/web/commit/984122bb157be39910200986a8c78dcdc8d5b123)

**Comment by samkanga** [comment]
@p-netm Please assist in deploying the reverted fix_problem task to the production instance.
