### ISSUE TITLE
Offline Maps Download Not Working

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#114]
The offline Maps download on EUSM are not working. When a user  who is online selects a location and hits the download button, an error is returned that reads `Error: Location has no service points` See a sample screenshot below:

![image](https://user-images.githubusercontent.com/5908630/217775400-f47ad500-fed4-430b-b8be-5770810a8237.png)

**Comment by Mstjamush** [comment]
The Download seems to hang mid way when internet is turned off.

Also, deletion of downloaded maps doesn't seem to work

**Comment by samkanga** [comment]
The down load should not work when offline. The internet is needed for the download process. Also, due to Mapbox limitations we are unable to download maps at regional level and have taken this down to districts and added a restriction so that only 1 map can be downloaded at a time.

**Comment by Mstjamush** [comment]
Fixed
