### ISSUE TITLE
Updating Test Missions on EUSM Production with [Test] Tag

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#122]
We have a number of test missions on EUSM production. These are being counted in some of the indicators on Akuko such as the count of missions created over a given duration of time. To distinguish them and filter them out, we need to add a [Test] tag to the respective missions. Active/Completed/Retired mission names cannot be edited. An example of the name update is `Test Mission 4` that would read `[Test] Test Mission 4` and `Landy Test Tulear` that would read `[Test] Landy Test Tulear` 

Below is the list of missions to be updated and their IDs.

1. Bureau Fenerive Test 2 - c2c3655a-2c7e-5b59-92fd-3d0ffd240fb1
2. EK Test missing - 28be518e-1769-5385-853f-6f2b79859c8a
3. Landy Test Tulear - bfe0160c-a035-5154-b471-ad8247b76857
4. Landy test 2 tulear - 2d872eb9-c919-5fdd-acdb-b4a8fc813c46
5. Test 2 Fenerive 14 juin 2022 - b9904ffa-7fd1-583f-bf2a-644bca41adb2
6. Test Awa Fort Dauphin - fdce8808-aa95-53a2-addd-5daeb07b93ed
7. Test Bureau Ambovombe - 69a92c7e-aafb-5d16-a615-cd457d3e639f
8. Test Bureau Ambovombe 1 - c3a3833e-4c58-52ac-ac83-6ec101d06eb7
9. Test Bureau FD 2 - 4475f5d3-3ef0-53a2-afb2-75178da24cbe
10. Test Bureau Fort Dauphin - 1b4e976e-5d27-516f-9819-634edc8bd46a
11. Test Bureau Tulear mai-juin 2022 - 547a3134-3af3-5173-8109-7872ad6e3cf5
12. Test Fenerive 13 juin 2022 - 5cbde365-3fa8-578c-bf23-e917e426c7cf
13. Test Mission 3 - 828a1e82-2417-50ab-a633-5cdbb8d39524
14. Test Mission 303 - f9470879-0ea1-5126-9372-e9feaf6b6b7a
15. Test Mission 4 - 76665b51-2b3f-5255-9a27-4f8b0a3a2c99
16. Test Mission October - 486ba2af-fad2-5fd5-bf0a-f9a3efc9ddcb
17. Test Mission5 - 228ecd64-3ca3-5458-8520-3e4cc91a37f7
18. Test Mission 2 - c4e24df3-695b-5c96-906c-0e276f07a5f8
19. Test Mission 2 - eb99f622-b743-5e3b-b7cf-63cc935f2302
20. Test Mission1 - b41a7825-de7d-5778-a0e7-5cfa23a6f859
21. Test3 - 39201494-28c8-5b4e-b900-6b656182d82f

**Comment by p-netm** [comment]
done
