### ISSUE TITLE
Add language dropdown to the app

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#13]
Would language dropdown go below the district selection?

https://marvelapp.com/prototype/1296hh24/screen/71758172

**Comment by rowo** [comment]
Seems like there is no language pull down or settings in Reveal. I think we can do something like this: https://marvelapp.com/prototype/1296hh24/screen/71758172

I guess the button should be written in the original language i.e. "Langue: Français" instead of "Language: French".

**Comment by cafootitt** [comment]
Thanks Roger.

**Comment by cafootitt** [comment]
Closing. This will be implemented as part of #2
