### ISSUE TITLE
 Location hierachy not loading and service point created on web not available on the andoid app

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-eusm#133]
v.0.2.1 -release (Production)
User had an issue connecting to the app. 
![image](https://github.com/onaio/fhir-web/assets/58034047/6eb44ef5-aa88-4f5c-9673-1456d66fa53c)

Once connected - user could not obtain the locations from the side panel - it only shows Madagascar and not the hierarchy below it. 
![image](https://github.com/onaio/fhir-web/assets/58034047/f2307af5-566a-40eb-a602-46d976d86b5a)

When they uninstalled and reinstalled the app - user could load the loction hierachy but could not find any service points even though some were created and assigned for the mission.
![image](https://github.com/onaio/fhir-web/assets/58034047/a52e0cee-943d-47b0-8f22-f70917d93bbc)

Could be related to https://github.com/onaio/fhir-web/issues/1308

**Comment by hamza-vd** [comment]
@AnnieMungai 

> Once connected - user could not obtain the locations from the side panel - it only shows Madagascar and not the hierarchy below it.

There must be an error that occurred while syncing locations to the device. We might need to investigate further on it. Is it possible to get a specific scenario? I have tried to replicate this on debug with `demo` user. I have assigned/un-assigned multiple missions but was not able to reproduce this. 

> When they uninstalled and reinstalled the app - user could load the loction hierachy but could not find any service points even though some were created and assigned for the mission.

This happens when the service locations assigned to a Region do not have a `Lat/Lng` value assigned to them. The service points will appear in the `List` (button at top right corner) but they will not be plotted on the map unless coordinates are assigned to them, which will lead to this error dialog. We might need to make sure first that the service points under the region assigned to the user above had their `Lat/Lng` values or not.

**Comment by AnnieMungai** [comment]
@hamza-vd does this mean the error that is popping is specific to the map and not the whole app?

**Comment by hamza-vd** [comment]
@AnnieMungai Yes. The service points should still be visible under list view screen

**Comment by AnnieMungai** [comment]
@hamza-vd this is not the case on production - I am not able to view any service points for assigned regions (see video below). 

https://github.com/opensrp/opensrp-client-eusm/assets/58034047/31240198-b2d0-4077-89c5-9897524580c6

**Comment by hamza-vd** [comment]
@AnnieMungai 
Is it possible to make sure that the service points assigned to the region have valid inventories? By valid I mean their **Accountability end date** should not be expired.

**Comment by AnnieMungai** [comment]
The following are sample service points assigned to 2 different missions cc @hamza-vd @peterMuriuki 
- CHRR - Madagascar > ANALANJIROFO > Fenerive Est > Fenoarivo Atsinanana Ambonivohitra - 93cd1649-db6d-41bc-a5bd-4f6e61ab9ce2
- Warehouse - Madagascar > ANALANJIROFO > Fenerive Est > Fenerive Est - 70999acd-cd91-4c90-85a6-daafafd5ecea
- DRSP - Madagascar > ANALANJIROFO > Fenerive Est > Fenerive Est - e980061e-6353-4028-80ed-403e84467750
- Warehouse - Madagascar > ATSINANANA > Toamasina I > Cu Tamatav - 82ef42ce-fe2b-4b4c-a590-d0c09395190e
- DRSP- Madagascar > ATSINANANA > Toamasina I > Cu Toamasina 1er - b434154a-7657-4cea-845e-51d63f799eea

**Comment by hamza-vd** [comment]
@AnnieMungai  
Upon further debugging, I discovered no tasks for the selected mission were generated. This needs to be further investigated. 
cc: @bennsimon

**Comment by bennsimon** [comment]
@AnnieMungai I have noted some product catalogue validation issue:
```
Caused by: java.lang.IllegalStateException: Code value: 'Chlorine, salt water treatment, ' must end with a non-whitespace character
Caused by: java.lang.IllegalStateException: Code value: 'IEHK2017, kit, Suppl.1 Medicines  (PPOS)' must not contain consecutive spaces
Caused by: java.lang.IllegalStateException: Code value: 'Tente ' must end with a non-whitespace character
```
This affects the task creation of some stocks.

**Comment by bennsimon** [comment]
These additional plans didn't trigger task generation:
Query used
```sql
select distinct(pm.identifier),json->>'name' as name, json->>'status', json->'effectivePeriod'->>'end' as end_date, pm.date_edited from core.task_metadata tm right join core.plan pm on tm.plan_identifier=pm.identifier where tm.plan_identifier is null and json->>'status'='active' order by end_date desc;
```


```
              identifier              |                                 name                                  | ?column? |    end_date     
--------------------------------------+-----------------------------------------------------------------------+----------+-----------------
 8527016f-bfaa-5eb8-bf5f-853b926b5ca9 | 2023 Décembre Analanjirofo Randriamitantsoa Safidinantenaina          | active   | 2023-12-29T0000
 2887f13e-6eeb-5552-bad4-1a6d4aa3a482 | 2023 Décembre Atsimo Andrefana Michaela Ranaivo                       | active   | 2023-12-22T0000
 54723866-0f07-50df-813f-d45a39ad7d4b | 2023 Décembre Vakinankaratra Angelin Rabezandriny                     | active   | 2023-12-22T0000
 a0405267-a7e2-5c1c-a24b-d3163cc7374a | 2023 Décembre Boeny FenoMamy ZO                                       | active   | 2023-12-21T0000
 01d36bbb-e130-507f-9b4c-7e97e5132fc3 | 2023 Décembre Analanjirofo RAKOTONIRINA Haingo                        | active   | 2023-12-20T0000
 7e5fb37e-8b0b-569b-a0af-63d0de915a68 | 2023 Décembre Boeny                                                   | active   | 2023-12-20T0000
 12ae4989-ac65-542b-b2fa-3d68cc968d29 | 2023 Décembre Androy IMANOMBO Ando RATSIMBA                           | active   | 2023-12-16T0000
 2babcd48-cbda-54f4-b0ae-64e5061ef3ae | 2023 Décembre Atsimo Andrefana Rahajamanana Colette                   | active   | 2023-12-15T0000
 80558eac-754c-53d0-a573-3be9d58087bb | 2023 Décembre Atsimo Andrefana Rivo Pascal Randrianatoandro           | active   | 2023-12-15T0000
 8d79223f-0197-59f5-8eb3-4b3e3cd891b0 | 2023 Décembre Atsimo Andrefana RANDREMBASON Sitraka Lovasoa           | active   | 2023-12-15T0000
 6e21b95d-519f-5b80-98f1-a373d1134717 | 2023 Décembre Vatovavy Fitovinany RALALAHARIMINO Eulalie Lucie        | active   | 2023-12-12T0000
 5faa56e0-e6eb-59fc-a6e8-6b53527a872f | 2023 Décembre Atsimo Andrefana Mamiandosoa Rabenjalinoro              | active   | 2023-12-10T0000
 a75d3f49-8397-5925-b07b-5fe23c3a2332 | 2023 Décembre Anosy Zafindrakemba Melanie Iolande                     | active   | 2023-12-10T0000
 f359fd94-ca40-5f1c-b383-00fe94915c5e | 2023 Décembre Atsimo Atsinanana Augustine Marie Léonide RASOAHENIKAJA | active   | 2023-12-10T0000
 3b78da72-d3e8-579b-b56b-e4ee6ce29ad6 | 2023 Décembre Vatovavy Fitovinany RALALAHARIMINO Eulalie Lucie        | active   | 2023-12-09T0000
 4a09bea5-1b49-57d0-8ac0-6557a75341d5 | 2023 Décembre Atsimo Andrefana RAZANABONINAHITRA Famatanantsoa        | active   | 2023-12-09T0000
 9fd478f3-25e4-5d6f-bd46-cd1093730012 | 2023 Décembre Anosy Zakariasy Randrianarivony                         | active   | 2023-12-09T0000
 a0a8eb4c-53bf-5ece-be84-be2eac3af0ff | 2023 Décembre Boeny Razanakoto Aubry                                  | active   | 2023-12-09T0000
 b1016508-9536-5469-84de-49edfccb57c9 | 2023 Décembre Atsimo Andrefana Rahajamanana Colette                   | active   | 2023-12-09T0000
```

To trigger task generation:
- Obtain the plan object (using the GET endpoint).
- Hit the plan POST endpoint with the plan obtained above. Task generation should begin automatically.

**Comment by AnnieMungai** [comment]
Users can now see the locations and associated service points.
