### ISSUE TITLE
[EUSM] OpenSRP server not returning location hierachy on web

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-eusm#138]
When you navigate on OpenSRP web and try to fetch the locations, it seems the OpenSRP server is not sending the locations. The location hierarchy is non-existent. See screen shot below: 

![image (18)](https://github.com/opensrp/opensrp-client-eusm/assets/58034047/c2eba9f8-2ee9-4f33-852d-1aed5f4ac3b0)

**Acceptance Criteria**
- [x] Location hierachy should be returning results on web from the OpenSRP server. User should see the location hierachy. 
- [x] User should be able to add locations to the hierarchy.

**Comment by hilpitome** [comment]
This was fixed by updating the parent_id for the location Madagascar to an empty string. Refer to issue [547](https://github.com/opensrp/opensrp-server-core/issues/547) on opensrp-server-web

**Comment by AnnieMungai** [comment]
LGTM!
