### ISSUE TITLE
Create Android app icon

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#14]
We also need an app icon. After discussing with Benn, this can just be the clipboard icon by itself.

**Comment by rowo** [comment]
@cafootitt what is there to discuss with Benn? Isn't this more of a client approval thing?

**Comment by cafootitt** [comment]
@rowo Oh ok, well Benn asked for the icon, so I assumed it needs to be in a particular format that he doesn't have right now. If you're not sure what you need to do for this, then I'll chat with benn and make the ask more specific.

**Comment by rowo** [comment]
I am not sure. If your conversation with Benn is just about format (resolution and file type) and not content (what is on the icon), then that's one thing. If it's about content, that's where I'm saying ... isn't that more of a Gareth thing or something I work with him to define?

**Comment by cafootitt** [comment]
@rowo I messaged you on Slack in response to this, last week. It's just about format.

**Comment by rowo** [comment]
@cafootitt We can do better than this next time. Even if there isn't dedicated budget on the project, that doesn't mean we have to make something lackluster.

![eusmicon](https://user-images.githubusercontent.com/1584163/98202135-5666bf00-1eff-11eb-99f4-645c93691565.png)

**Comment by cafootitt** [comment]
@rowo Ok, this is a bit unexpected, but thanks for sharing that. We could do something more. I didn't think that was an option. What do you have in mind?
