### ISSUE TITLE
Newly added service points not available on Android

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-eusm#140]
Service point: Container Manakara - a warehouse was created on web and assigned a mission. However, this service point is not visible on the android device (related to #137 ). This is happening to all newly added service points. 

Region: VATOVAVY FITOVINANY
District: Manakara Sud
Town : Manakara
Type: Warehouse
Latitude/longitude: -22.153707, 48.017596
Service point ID: 48365772-08d7-465c-9637-792aceccda2c

Note! This issue is recurring even after it is addressed and passed QA.

**Required**
- [ ] Trigger the newly added service points manually to unblock a team in the field. 
- [ ] Find out why newly added service points are not seen on the android.

**Acceptance criteria**
All newly created servcie points with their tasks are available on android. e.g. Container Manakara service point .

**Comment by hilpitome** [comment]
Fixes done for this issue
1. Sanitize the products that were created with extra spaces
2. Regenerate the tasks in the affected missions

**Comment by AnnieMungai** [comment]
Created a new SP and assigned a product - the SP was visible on the android. LGTM!
