### ISSUE TITLE
Integrate tasking library to EUSM

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#17]
https://github.com/OpenSRP/opensrp-client-tasking

**Comment by cafootitt** [comment]
Hopefully PR submitted by EOD 16 Nov.

**Comment by bennsimon** [comment]
Tracked here https://github.com/OpenSRP/opensrp-client-tasking/pull/29

**Comment by cafootitt** [comment]
PR review still ongoing.
