### ISSUE TITLE
Integrate stock library to EUSM

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#18]
- Add extra columns in stock and stock type tables to support additional properties for ProductCatalogue and Inventory.
- Add StockTypeService that will sync all the ProductCatalogues to the device.
- Update StockService to support changes for Inventory sync

**Comment by cafootitt** [comment]
Benn - added new columns, testing the new APIs that were created.

**Comment by bennsimon** [comment]
Tracked here https://github.com/OpenSRP/opensrp-client-stock/pull/105

**Comment by cafootitt** [comment]
Majority of work is done, need to update the stock endpoint for this. 0.5 days.

**Comment by bennsimon** [comment]
> Tracked here [OpenSRP/opensrp-client-stock#105](https://github.com/OpenSRP/opensrp-client-stock/pull/105)
PR has been merged
