### ISSUE TITLE
Create test data for Inventory and product catalogue

### ISSUE THREAD

**Issue by bennsimon** [OpenSRP/opensrp-client-eusm#20]
We need sample data of inventories and product catalogue uploaded to the server for testing purposes. Local data wont serve us as much cause we need to test syncing of theses entities.

**Comment by cafootitt** [comment]
Product catalogue: https://docs.google.com/spreadsheets/d/103iREDv7AzIP1rCVrWJRct2ACJXn92pEplCmSWwhCbg/edit#gid=0

For the inventories, we can just randomly pick some products from the catalogue to assign them to service points, for testing for now.
