### ISSUE TITLE
Change the size of the icons for 'service point check' task & 'record GPS' task

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#21]
- [ ] Can we have the service point check icon shown [here](https://marvelapp.com/prototype/1296hh24/screen/71758788/handoff) in the same size as the default product image icon?

- [ ] Can we have the record GPS icon shown [here](https://marvelapp.com/prototype/1296hh24/screen/73379016/handoff) in the same size as the default product image icon?

**Comment by rowo** [comment]
Handoff: https://marvelapp.com/prototype/1296hh24/screen/73379016/handoff

Asset links weren't working at the time, so here're images too:

![capture gps](https://user-images.githubusercontent.com/1584163/100694374-ef50f480-335c-11eb-8adf-22e34db26013.png)
![service point check](https://user-images.githubusercontent.com/1584163/100694377-ef50f480-335c-11eb-88d8-838280dc9fce.png)

**Comment by cafootitt** [comment]
Thanks very much!
