### ISSUE TITLE
Include plan ID in the Flag Problem stock image submission

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#22]
As per our conversation today to finalize the event to JSON mapping:

We need to include the plan ID, so that if a stock item is included in a future mission, the image won't be overridden. We can remove the plan ID in the image file name export though, so the user doesn't see it.

**Comment by bennsimon** [comment]
Ok, Will make the change.

**Comment by cafootitt** [comment]
@bennsimon I'm unable to QA this myself, so please close if you're reviewed and it's working ok.

**Comment by bennsimon** [comment]
@cafootitt yeah i have tested and it works
