### ISSUE TITLE
Add boolean field in obs for Flag Problem to indicate if image is submitted

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#24]
Required for the mission data export on OpenSRP web.
cc @rehammuzzamil

**Comment by bennsimon** [comment]
@cafootitt For this can we just check the `flag_problem` reason in Obs if its `not_there` then there is no image else there is.

**Comment by cafootitt** [comment]
thanks, Benn, that makes sense to me from my perspective, but what about @rehammuzzamil?

**Comment by rehammuzzamil** [comment]
Does this mean at a time only one property would be there in obs either `not_there` or `not_good`?
If it is correct, then this makes sense @bennsimon.

**Comment by cafootitt** [comment]
@rehammuzzamil only one property would be in the obs, and that would be any of the following: 

`not_there`
`not_good`
`misuse`

If `not_good` or `misuse`, the picture is required, otherwise, if answer is `not_there`, there will never be an image.

**Comment by rehammuzzamil** [comment]
That makes sense. Thanks, @cafootitt !

**Comment by cafootitt** [comment]
Great, thanks!
