### ISSUE TITLE
Add EUSM logo version for the web

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#28]
![Screen_Shot_2020-12-04_at_10_29_26_AM](https://user-images.githubusercontent.com/3488986/101182206-b27b4b00-3645-11eb-98f1-be4aef8f8361.jpg)

**Comment by rowo** [comment]
@cafootitt here's the logo
![EUSM-web-logo](https://user-images.githubusercontent.com/1584163/105043328-69375d00-5a33-11eb-8f8b-135edb633558.png)
https://marvelapp.com/prototype/f3igd3h/screen/73966532/handoff

**Comment by cafootitt** [comment]
Much thanks

**Comment by cafootitt** [comment]
Deployment on 29 Jan 2021 - lgtm
