### ISSUE TITLE
UI clean up on the product info page

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#32]
- [x] A
- [x] B
- [x] C
- [x] D

![Screenshot_20201210-135250_eusm](https://user-images.githubusercontent.com/3488986/101823622-f4fbc680-3b22-11eb-9f3e-58fbe9c958d9.jpg)

**Comment by bennsimon** [comment]
@cafootitt For C could you direct me to the assets?

**Comment by cafootitt** [comment]
@rowo Can you add these icons to the assets in Marvel handoff, or just post them to this issue?

**Comment by rowo** [comment]
@bennsimon @cafootitt 
Here are the icons:
![icon_there](https://user-images.githubusercontent.com/1584163/101959809-12d53400-3bd4-11eb-84fb-83e3b1f587fe.png)
![icon_condition](https://user-images.githubusercontent.com/1584163/101959810-136dca80-3bd4-11eb-807b-a90070fec8ac.png)
![icon-used](https://user-images.githubusercontent.com/1584163/101959812-136dca80-3bd4-11eb-8fa2-d4ec00e9cd32.png)

@bennsimon For D, how are you making that graphic word for all screen sizes? Would it make more sense to do the border in Android itself? Or if that's too troublesome, we can move away from their styling and do something easier to scale to different proportions.

**Comment by bennsimon** [comment]
@rowo i can scale the default image to fit the entire screen. But for the actual images am thinking we let the image fit on the given height since different images might have different dimensions.

Its okay to work with the default image the way it is since its the only one with a border.

A textView however can scale easily.

**Comment by rowo** [comment]
@bennsimon Okay, thanks on the default image. 

On user-provided images it would be ideal if it can fit within the width or height (as max), but height-only is probably the next best guessing what kind of images they'll upload. Is it possible for the user to drag-zoom the image easily (sometimes happens in news apps as an easier way than a fullscreen image viewer)? That would be another nice to have but not needed right now.

**Comment by bennsimon** [comment]
@rowo For the 

> @bennsimon @cafootitt
> Here are the icons:
> ![icon_there](https://user-images.githubusercontent.com/1584163/101959809-12d53400-3bd4-11eb-84fb-83e3b1f587fe.png)
> ![icon_condition](https://user-images.githubusercontent.com/1584163/101959810-136dca80-3bd4-11eb-807b-a90070fec8ac.png)
> ![icon-used](https://user-images.githubusercontent.com/1584163/101959812-136dca80-3bd4-11eb-8fa2-d4ec00e9cd32.png)
> 
> @bennsimon For D, how are you making that graphic word for all screen sizes? Would it make more sense to do the border in Android itself? Or if that's too troublesome, we can move away from their styling and do something easier to scale to different proportions.

@rowo Can we have this icons be of the same size. If possible can have them in (vector) .svg format.

**Comment by rowo** [comment]
@bennsimon I dm'd you the svg's

**Comment by cafootitt** [comment]
16 Dec 2020 build - looks great, good work!
