### ISSUE TITLE
Error message on login 

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#33]
Getting kicked out of the app occasionally, and it lands on the login page with this error message:

![Screenshot_20201210-140102_eusm](https://user-images.githubusercontent.com/3488986/101823768-312f2700-3b23-11eb-8dd0-892d440ea9dc.jpg)

**Comment by rowo** [comment]
Sorry, I didn't get a screenshot but I may have gotten a variation of this message... something like the time was changed and so it logged me out. Can't say for sure though.

**Comment by bennsimon** [comment]
@rowo noted

**Comment by bennsimon** [comment]
@cafootitt updated Session Idle timeout on Keycloak, i think its enough to fix the issue. Kindly observe and let me know if it fixes it.

**Comment by cafootitt** [comment]
@bennsimon Thanks, I'll re-open the issue if this is observed again. It didn't happen consistently. Thanks.
