### ISSUE TITLE
Add Transifex integration

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#34]
LOE: 0.5-1 day, plus time for PR reviews, testing, etc.
@bennsimon to provide implementation details when he picks up this issue.

**Comment by cafootitt** [comment]
QA on 18 Jan 2021 - there are 98 strings appearing in Transifex

- [ ] `url_separator` string key text is just a `/`, so should that be its own string in transifex? Should we remove this string key?
- [ ] `reveal` string key probably shouldn't be in EUSM library in Transifex
- [ ] Should we combine or re-use `plan` and `campaign` key strings, as they are both the same?
- [ ] `canton` key string is probably from Reveal, not EUSM-related; should we remove it?
- [ ] `operator_with_middle_dot` key string has this as a label: `User :  &#183`; Should the `&#183` be removed? What does this mean?
- [ ] `hamburger_menu` and `menu` key strings are the same label - should we re-use or remove one?
- [ ] Should we update the English lablel of `plans` to be "Missions"?
- [ ] Similarly, should we update the English label of `structures` to be "Service points"?
- [ ] Ditto for `fetching_structures_title` - should we update the English label to be "Fetching service points"?
- [ ] Ditto for `fetching_structures_message` key string
- [ ] Should we update `plans_download_on_progress` key string English label to reference missions, not plans?
- [ ] `hello_blank_fragment` is this needed?
- [ ] I don't see a key string for "GPS unknown" on the list page
- [ ] I don't see a key string for the "km away" to show how far away a service point is
- [ ] I don't see the strings for any of the json forms - we need to use the JMAG tool to add these key strings automatically
- [ ] Will the French translations for things like the product catalogue info (e.g. 'is it there' text for each product - will that be added on OpenSRP web and the android app will be able to display the french text, or do we need to add these strings separately for mobile?
- [ ] I think we have French translations already for a large part of the native form library, so should we go ahead and pull those strings in?
- [ ] We'll need to have Roger create French versions of the images that have English text. Can you help me verify if this list is comprehensive:
- App logo
- "No photo available" image
- "No generic photo available" image
- Am I missing any other image?

**Comment by bennsimon** [comment]
> QA on 18 Jan 2021 - there are 98 strings appearing in Transifex
> 
> * [ ]  `url_separator` string key text is just a `/`, so should that be its own string in transifex? Should we remove this string key?
**removed**
> * [ ]  `reveal` string key probably shouldn't be in EUSM library in Transifex
**removed**
> * [ ]  Should we combine or re-use `plan` and `campaign` key strings, as they are both the same?
**for EUSM yeah**
> * [ ]  `canton` key string is probably from Reveal, not EUSM-related; should we remove it?
**removed**
> * [ ]  `operator_with_middle_dot` key string has this as a label: `User :  &#183`; Should the `&#183` be removed? What does this mean?
**this add a middle dot,  its decimal code value is &#183 (its a special character)** 
> * [ ]  `hamburger_menu` and `menu` key strings are the same label - should we re-use or remove one?
**we can leave this they are used in different places**
> * [ ]  Should we update the English lablel of `plans` to be "Missions"?
**updated**
> * [ ]  Similarly, should we update the English label of `structures` to be "Service points"?
**updated**
> * [ ]  Ditto for `fetching_structures_title` - should we update the English label to be "Fetching service points"?
> * [ ]  Ditto for `fetching_structures_message` key string
> * [ ]  Should we update `plans_download_on_progress` key string English label to reference missions, not plans?
**updated**
> * [ ]  `hello_blank_fragment` is this needed?
**removed**
> * [x]  I don't see a key string for "GPS unknown" on the list page
**added**
> * [ ]  I don't see a key string for the "km away" to show how far away a service point is
**its dynamic see `distance_from_structure`, kindly inform if the work `km` or `m` will be translated**
> * [ ]  I don't see the strings for any of the json forms - we need to use the JMAG tool to add these key strings automatically
**Can we move this to a different issue**
> * [ ]  Will the French translations for things like the product catalogue info (e.g. 'is it there' text for each product - will that be added on OpenSRP web and the android app will be able to display the french text, or do we need to add these strings separately for mobile?
**separate if better**
> * [ ]  I think we have French translations already for a large part of the native form library, so should we go ahead and pull those strings in?
**Can we can move the Native Forms MultiLanguage support to a different issue**
> * [ ]  We'll need to have Roger create French versions of the images that have English text. Can you help me verify if this list is comprehensive:
> * App logo
> * "No photo available" image
> * "No generic photo available" image
> * Am I missing any other image?
**i think the list is okay**

**Comment by cafootitt** [comment]
22 jan 2021 - lgtm - great work!
