### ISSUE TITLE
Cancel "Fix problem" task if "Flag problem" task is undone by the user

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#37]
Steps to replicate:

- Complete a product check task for a service point - flag problem
- The "fix problem" task should be triggered and appear in the list
- Undo the flag problem task
- The "fix problem" task should be canceled

If the "fix problem" task is already completed by the user, then should we force the user to "undo" the fix problem task? Or would we be able to undo that automatically as well? Or, should we disable "undoing" on the flag problem task if the fix problem task has already been completed?

**Comment by bennsimon** [comment]
This is done but there is an issue on Location/UserAssignments which is kind of blocking it, during test we added a work around for the test data.

**Comment by cafootitt** [comment]
27 Jan 2021 release - lgtm

@bennsimon are you referring to https://github.com/OpenSRP/opensrp-client-eusm/issues/44?

**Comment by bennsimon** [comment]
@cafootitt yeah i was

**Comment by cafootitt** [comment]
#44 is finished, so closing this issue as well, since it passes QA.
