### ISSUE TITLE
Pagination bug 

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#39]
There are only 4 service points listed, but pagination is showing page 1 of 17. If you tap next and go to page 2, it's a blank page and there's no way to get back to page 1.

![Screenshot_20210118-155317_eusm](https://user-images.githubusercontent.com/3488986/104962034-92a9a780-59a5-11eb-8a26-9d2142afc609.jpg)
![Screenshot_20210118-155319_eusm](https://user-images.githubusercontent.com/3488986/104962036-93423e00-59a5-11eb-8897-e362104ca3a5.jpg)

**Comment by bennsimon** [comment]
noted

**Comment by cafootitt** [comment]
27 Jan 2021 release - lgtm, fixed.
