### ISSUE TITLE
User Assigned locations dont include the assigned Location

### ISSUE THREAD

**Issue by bennsimon** [OpenSRP/opensrp-client-eusm#44]
If a user is assigned to LocationA its children locations are the ones synced to the device. We need the actual location to be also included e.g LocationA since in EUSM we use District as Operational Area and users are assigned to districts.

**Comment by bennsimon** [comment]
Linked to https://github.com/OpenSRP/opensrp-client-core/pull/731

**Comment by cafootitt** [comment]
This is done and merged, closing
