### ISSUE TITLE
Add French versions of the images in the EUSM app

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#47]
- [x] "No photo available" image: https://marvelapp.com/prototype/1296hh24/screen/71758788
French: Aucune photo disponible

- [x] "No generic photo available" image: https://marvelapp.com/prototype/1296hh24/screen/71758789
French: Aucune photo disponible (This is the same as above, but adding "generic" to the French translation sounds a bit weird, so I think we'd want to use the same one)

**Comment by rowo** [comment]
@cafootitt 

Small image: https://marvelapp.com/prototype/1296hh24/screen/76224148/handoff
Large image: https://marvelapp.com/prototype/1296hh24/screen/76224147/handoff

**Comment by cafootitt** [comment]
27 Jan 2021 - unable to QA this - I need a service point that has the generic images in it.

**Comment by cafootitt** [comment]
V0.0.3 release - lgtm
