### ISSUE TITLE
Mission data download returning both answer choice labels and answer choice key values

### ISSUE THREAD

**Issue by cafootitt** [opensrp/opensrp-client-eusm#62]
Location id | Location name | Entity Type | Event Date | Event Type | Mission | Team | User | stock_id | product_id | product_name | flag_problem | product_not_there_reason | product_not_there_reason_other | product_not_good_condition_reason | product_not_good_condition_reason_other | product_misused_reason | issue_details |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
34fba564-4062-4b15-95fc-3e6652776542 | Ambohimanarina | product | 2021-03-03T03:00:00.000+03:00 | flag_problem | Carolyns 3 March mission | Carolyns team | carolyn | 700d0d26-5c56-46fb-bfc8-98fcbaaaaaa7 | 18 | Poste DLM | [["Le produit nest pas en état de fonctionnement"]] | [] | [] | [["worn_broken"]] | [] | [] | [["broken"]] |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
244de12a-e4d8-4fd9-924a-520275b00cdb | KOFIAM Soavimasoandro BLV3593 | product | 2021-03-03T03:00:00.000+03:00 | flag_problem | Carolyns 3 March mission | Carolyns team | carolyn | b955d8ff-6170-4833-b082-42bd3648f750 | 18 | Poste DLM | [["Le produit nest pas là"]] | [["lost_stolen"]] | [] | [] | [] | [] | []

We agreed the answer choice label should be returned for all fields. We'll need to check all other event types as well:
- [ ] Flag problem
- [ ] Fix problem
- [ ] Service Point Check

**Comment by cafootitt** [comment]
LOE - 0.5 days

**Comment by bennsimon** [comment]
@rehammuzzamil These are the fields that need to me updated:
**Flag problem**
- not_good
- not_there
- misuse

**Fix Problem**
- problem_fixed

**Service Point Check**
- other_products_action
- other_needed_products
- service_point_good_order

**Comment by cafootitt** [comment]
LOE - 2-3 hours

**Comment by cafootitt** [comment]
PR on client core under review, then server web work will take 2-3 hours.

**Comment by rehammuzzamil** [comment]
@bennsimon Initially we were reading data from the **values** field based on the form submission field input. Are we thinking to read from the **keyValPairs** now, but I believe it is still dependent on the values field? Can you please confirm this? 

A current sample of reading through the JsonPath library is shown in below:
` "$.obs[?(@.formSubmissionField=='problem_fixed')].values"`

**Comment by cafootitt** [comment]
@bennsimon can provide input when he's back from leave on Monday.

**Comment by bennsimon** [comment]
@rehammuzzamil Yeah we will be reading from **keyValPairs**. The pair will only have one entry.
