### ISSUE TITLE
Enable the button to see your GPS location on map view

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#63]
- [x] Enable the button to pinpoint your GPS location on the map
- [x] The map should redirect to your GPS location whenever you tap the button

**Comment by bennsimon** [comment]
@cafootitt Where position should the button be? ... at the moment if defaults to top right of the map.

**Comment by cafootitt** [comment]
I don't know, so let's go with the default for now. Are you saying we can place it anywhere on the map view? What are the options, just so I know?

**Comment by bennsimon** [comment]
yes we can.

**Comment by cafootitt** [comment]
Looks fabulous, thanks!
V0.0.7 (10 March 2021 build)
