### ISSUE TITLE
Implement the four forms

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-eusm#7]
Mockup: https://marvelapp.com/prototype/7d6gbea/screen/73387487
xlsforms for the four forms are in this [folder](https://drive.google.com/drive/u/1/folders/1NUBWUbszn6-P6sEFjIFNM7qJmA5tBWOI).

- [x] Capture GPS form opens when the user taps on the "Capture GPS" task in the service point list. Submitting the form completes the task and saves the GPS coordinates to the service point. It would be nice if the GPS coordinates could be used to already display the service point on the map view and to replace the "GPS unknown" label with the distance to the user, but if this takes more than like an hour to do, please leave it.

- [x] Service point check task opens the Service Point Check form. Submitting this form completes the task in the list.

- [x] Flag problem form opens when you tap on the "Flag problem" button on the product info page. Submitting this form completes the task for that product and also triggers the "Fix problem" task, which appears in the task list for that service point.

- [x] The Fix problem form opens when you tap on any Fix problem task in the list. Completing this form completes the task.

Note: please use existing native form library widgets only. Don't develop anything new. Next and Submit buttons can use existing native form library widgets.

**Comment by cafootitt** [comment]
This was blocked until the tasking model was finalized, which it now is: https://github.com/OpenSRP/web/issues/171

Week of 30 Nov - Benn to work on generating tasks for these forms.

**Comment by bennsimon** [comment]
@cafootitt can we split this two tasks. The second task will be task generation based on planDefinition

**Comment by cafootitt** [comment]
@bennsimon Thanks, done - https://github.com/OpenSRP/opensrp-client-eusm/issues/26

**Comment by cafootitt** [comment]
V0.0.1 - lgtm. Some small clean up stuff moved to a new issue: #31
