### ISSUE TITLE
Distance to Service Point Showing a Dash

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#91]
There are instances where the distance to a water point is showing as a dash `- distance`. An example if for a water point at  Ampamata. See screenshot below:

![image](https://user-images.githubusercontent.com/5908630/131999546-268ef003-7685-466b-ad3f-3d7c1ab8c885.png)

**Comment by bennsimon** [comment]
@samkanga Is this still an issue?
