### ISSUE TITLE
Mission Assignment at Regional Level 

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#98]
The enhancements on mission planning will entail updating the EUSM web and EUSM Mobile to support team assignment at a regional level as opposed to the current district level. Teams/Users can be assigned to multiple regions if required. This assignment will enable users to download data related to all the regions that they will plan on visiting for offline missions. The users will be required to plan ahead and download the data with good internet connectivity. The enhancements on mission planning will entail updating the EUSM web and EUSM Mobile to support team assignment at a regional level as opposed to the current district level. Teams/Users can be assigned to multiple regions if required. This assignment will enable users to download data related to all the regions that they will plan on visiting for offline missions. The users will be required to plan ahead and download the data with good internet connectivity. 
- [ ] For the android client we need to have the ability to download data at regional level. This means that the hierarchy will show details from the regional level on the android client.
- [x] The location drop down needs to be updated to read Region and not District
- [x] The location selection needs to be updated from Multi-District Select to Multi-Region Select
- [x] All the service points in the selected region(s) should load on the map view

**Comment by Mstjamush** [comment]
Data is downloaded not as regions but as disctricts
