### ISSUE TITLE
Disable Automatic Sync When Online

### ISSUE THREAD

**Issue by samkanga** [opensrp/opensrp-client-eusm#99]
EUSM users indicated that they find the automated sync disruptive. The have requested that we disable the automated periodic data sync on EUSM Mobile when the devices are online. Users will be required to initiate manual sync when they complete missions. The client has also been made aware of the potential for data loss if the data was to get lost or damaged before sync is completed.

**Comment by samkanga** [comment]
@hamza-vd the EUSM team have reported that the automated sync is still running on the latest APK version 0.1.7 rc3. Please check if there was any logic that may have been left unchanged on automatic sync so we address it.

**Comment by hamza-vd** [comment]
@samkanga  I tested it on my end and could not reproduce the issue.  We can thoroughly test it further in the next APK.

**Comment by Mstjamush** [comment]
Cannot reproduce this
